//
//  Activities.swift
//  
//
//  Created by Alexandra Leonidova on 4/3/18.
//

import Foundation

class Activities{
    //data
    static var activitiesData = [
        "San Diego" : [
            "cultural" : [
                ["name" : "Old Town - Historic Park", "price" : "0", "description" : "Old Town San Diego State Historic Park presents the opportunity to experience the history of early San Diego by providing a connection to the past. Learn about life in the Mexican and early American periods of 1821 to 1872. Even today, life moves more slowly in this part of San Diego, where the hustle and bustle is balanced with history and fiestas. Visitors are offered a glimpse into yesteryear, as converging cultures transformed San Diego from a Mexican pueblo to an American settlement. San Diego became California's first Spanish settlement when a mission and fort were established here in 1769. Later, it passed into the hands of the newly made Mexican government before gaining statehood in the United States after the Mexican-American War.", "image" : "old_town"],
                ["name" : "USS Midway Museum", "price" : "21", "description" : "The USS Midway Museum is a maritime museum located in downtown San Diego, California at Navy Pier. The museum consists of the aircraft carrier Midway. The ship houses an extensive collection of aircraft, many of which were built in Southern California","image" : "midway_museum"],
                ["name" : "Balboa Park", "price" : "0", "description" : "San Diego is home to the nation’s largest urban cultural park with 15 major museums, renowned performing arts venues, beautiful gardens and the San Diego Zoo. Exploring the park grounds is a free and lovely thing to do, especially if you can catch a special event like a free Spreckels organ performance.", "image" : "balboa_park"]
            ],
            "outdoors" : [
                ["name" : "Potato Chip Rock Hike", "price" : "0", "description" : "The Mount Woodson hike leading to potato chip rock isn’t exactly for beginners as it’s rocky and uphill but the epic photo at Potato Chip Rock is one to frame. This 8-mile hike is in Poway.", "image" : "potato_chip"],
                ["name" : "Kayak Sea Caves", "price" : "70", "description" : "Off the coast of La Jolla Shores is a marine life-rich underwater park lined by seven sea caves. A variety of kayaking tours take you by the caves (and inside depending on conditions) while telling stories about how they were used during prohibition to smuggle booze into town. Along the way, you’ll no-doubt see leopard sharks, orange Garibaldi (California’s state fish), and friendly sea lions.", "image" : "kayak_sea_caves"],
                ["name" : "La Jolla Seals And Sea Lions", "price" : "0", "description" : "La Jolla’s seals and sea lions are used to people and you can get quite close to them, however, a respectful distance is encouraged. It’s easy to fill up a flash card with photos of them lazing along the coastline, often snuggled up against one another. Adults love this just as much as kids do. See my guide for how best to see the La Jolla seals and sea lions.", "image" : "la_jolla_seals"]
            ],
            "nightlife" : [
                ["name" : "Noble Experiment", "price" : "10", "description" : "Named after the “Noble Experiment” of Prohibition, this speakeasy is concealed inside a restaurant in the Gaslamp Quarter called Neighborhood, located at 777 G. Street. The Noble Experiment is the hardest of the San Diego speakeasies to find, since the hidden door is disguised as a wall of beer kegs close to the bathrooms. Simply push on the right side of the wall of beer kegs and you can enter the bar, with a red neon sign greeting you and a series of ornate brass skulls adorning the walls. Look around and you will notice the glowing chandelier, intricate paintings on the ceiling, white booths, and an overall Gothic style with dim red lighting to really set the mood of secrecy. The Noble Experiment is known for its excellent crew of mixologists, who can create a classy cocktail suited to your particular taste buds if you simply order the “Bartender’s Choice.” The bar pays homage to historical accuracy by only serving pre-Prohibition liquor, so don’t expect to find any vodka here. The average price for a cocktail is twelve dollars, but the bartenders take their time to produce only the best drinks, and they are definitely worth the price.", "image" : "noble_experiment"],
                ["name" : "Sunset Cruise", "price" : "39", "description" : """
                    At Cruise San Diego, our Sunset Cruise lets you experience a “sunset” side of Mission Bay that very few get to see, with our unique vessel designed especially for bay cruises, relaxing atmosphere, and awe-inspiring Pacific sunsets you are sure to enjoy this boat ride like no other.
                    This tour was designed specifically for anyone seeking a personal touch to an average sunset cruise.
                    Explore the pristine waters of our Mission Bay lagoon on our year round cruise inside this beautiful bay. You will enjoy a great selection of music and alcoholic beverages, allowing you to experience an intimate yet laid-back mood unlike any other sunset cruise in Mission Bay or San Diego.
                    Whether you are looking for a romantic outing, or a relaxing way to enjoy the evening sunset, our sunset cruise will satisfy any occasion.
                    """, "image" : "sunset_cruise"],
                ["name" : "Sevilla Night Club", "price" : "5", "description" : """
                    One of the most Popular & Longest running Nightclubs in San Diego's Gaslamp Quarter, Sevilla Nightclub was launched in 1987 and has been drawing fans of the many forms of Latin, Spanish Music & Dance ever since & has remained the Top Destination for San Diego Nightlife.
                    Sevilla Nightclub has an Intimate Ambiance, Roomy Dance Floor, VIP Bottle Service Amenities, a Plush Lounge area, and a Full Tapas Menu to choose from, delivering a unique atmosphere and the best in San Diego in Latin & Open Format DJs, Salsa, Bachata, & Merengue Dance Instructors, and Live Bands. Early arrival & VIP Bottle Service is always recommended, as there are often long lines outside.
                    """, "image" : "sevilla_night_club"]
            ]
        ],
        "Rome" : [
            "cultural" : [
                ["name" : "Colosseum", "price" : "15", "description" : "The Roman Colosseum is a testament to the architectural skills of the ancient Roman people and offers insight into the culture that celebrated the gladiator games at this huge entertainment arena. The first bloody fight ensued in A.D. 82, starting a tradition of battles between men and beasts in a public forum with crowds reaching 50,000. Outside of the Colosseum, look out for the photo opportunity beneath the Arch of Constantine, which was built in 315 to commemorate the victory of Constantine over Marcus Aurelius Valerius Maxentius.", "image" : "colosseum"],
                ["name" : "Vatican", "price" : "37", "description" : "Even though it's located in Rome, Vatican City has been an independent state since 1929 with its own flag, coins and stamps. It even has its own militia, the Swiss Guard, which protects this state, the Pope and the 800 full-time citizens and visiting residents. The first impressive site is St. Peter's Square itself designed by Bernini in the late 17th century. As long as you're dressed appropriately (no bare shoulders or shorts or skirts above the knee), you may enter St. Peter's Basilica and see Michelangelo's Pietá, a stunningly beautiful and sad sculpture. Continue up to the roof where you can take in the view of the large square and city beyond. Also contained in the Vatican's walls, the Vatican Museums hold Italian masterpieces, including Michelangelo's painted ceiling at the Sistine Chapel.", "image" : "vatican"],
                ["name" : "Galleria Borghese", "price" : "18", "description" : "The Galleria Borghese (English: Borghese Gallery) is an art gallery in Rome, Italy, housed in the former Villa Borghese Pinciana. At the outset, the gallery building was integrated with its gardens, but nowadays the Villa Borghese gardens are considered a separate tourist attraction. The Galleria Borghese houses a substantial part of the Borghese collection of paintings, sculpture and antiquities, begun by Cardinal Scipione Borghese, the nephew of Pope Paul V (reign 1605–1621). The Villa was built by the architect Flaminio Ponzio, developing sketches by Scipione Borghese himself, who used it as a villa suburbana, a country villa at the edge of Rome.", "image" : "galleria_borghese"]
            ],
            "outdoors" : [
                ["name" : "Villa Borghese Park", "price" : "0", "description" : "Dubbed the central park of Rome, Villa Borghese is a favorite for tourists and the locals. The resurrection of the park was commissioned during the 17th century and used by the Borghese and Bonaparte families. Though, it's not the largest park in Rome it is the most popular thanks to its central location and its beautiful scenery. Villa Borghese is also famous for its historical buildings and world-class museums such as the Galleria Borghese, a children's cinema, and a place where you can rent bikes. There are many places to sit and take some time out or have a picnic, but along the banks of little late are some of the prettiest.", "image" : "villa_borghese_park"],
                ["name" : "Roman Forum", "price" : "0", "description" : "In ancient Rome, the Forum was the center of city life, playing host to festivals, celebrations, funerals and rituals. The city grew around this grassy area that was empty marshland until the 7th century B.C. The area lost its luster and fell to waste around the 8th century and remained that way until excavations in the early 20th century. Today, you can pick up a map for a self-guided tour of the structures and arches or join a tour group for a more detailed history of the area. Then climb to the top of Palatine Hill for sweeping views of the city.", "image" : "roman_forum"],
                ["name" : "Food Adventure", "price" : "100", "description" : """
                    Formerly known as the Daylight Trastevere Food Tour, Trastevere for Foodies is a delight for the true foodie looking to get a real flavor of Roman life, through our food! With its narrow cobblestone streets and laneways, Trastevere is the most picturesque Roman neighborhood and one you need to visit during your stay. During the day, it’s like a small village with timeless and artisan shops serving the same local families for generations – many of which we’ll visit together, tasting the amazing food and exploring these local spots along the way.
                    On this 4-hour guided walking food tour we visit the colorful outdoor food market and meet some of the stallholders who have been selling their produce there for generations. You’ll also visit local food stores and talk to the wonderful families working hard to preserve Roman food traditions. This tour features some unique cultural and historical sites that few tourists get an opportunity to see. Join us for a day living like a true local!
                    """, "image" : "rome_food_adventure"]
            ],
            "nightlife" : [
                ["name" : "Rosati", "price" : "10", "description" : "Rosati opened on the Piazza del Popolo in 1922 and soon became a cornerstone of the vigorous, intellectual café and bar culture of Rome’s artists, poets and leftist thinkers. Sip on creative and interesting cocktails, and get into the spirit of the place with some invigorating intellectual discussion that continues on into the night.", "image" : "rosati"],
                ["name" : "Teatro dell’Opera di Roma", "price" : "80", "description" : "With acoustics to rival the world’s great auditoria, a night at Rome’s opera house can be a stirring and spectacular experience, with an acclaimed and talented opera company performing classics and recent works. The venue also has plenty for those left unmoved by opera, including ballet and classical symphony concerts. In the summer the opera company performs at the third-century ruins of the Baths of Caracalla, an outstanding and atmospheric open-air site that complements the passion and intensity of opera. It can make for a truly privileged and spectacular experience for long-time opera lovers and skeptics alike.", "image" : "teatro_dell_opera_di_roma"],
                ["name" : "Parco della Musica", "price" : "10", "description" : "An immense venue for arts, the stunning Auditorium Parco della Musica is at the forefront of Rome’s flourishing modern cultural life. It hosts the biggest names and performances across a dizzying variety of genres and disciplines, from music, dance, theater, comedy and cabaret to painting, photography, journalism, poetry, science and history. The wide-ranging program has something to suit all tastes, and the Auditorium’s four atmospheric performance spaces – from the intimate 300-person theater to the immense, 3,500-person summer amphitheater – are evocative complements to the events they host. The Auditorium stands above the still-visible ruins of an Ancient Roman villa, and its own design incorporates local materials and architectural traditions, giving a quintessentially Roman flavor to the experience of the arts that it offers. Exclusive private performances can be arranged and spectacular corporate functions, from cocktail receptions to lavish gala dinners, are eagerly accommodated and organized.", "image" : "auditorium_parco_della_musica"]
            ]
        ],
        "Beijing" : [
            "cultural" : [
                ["name" : "Summer Palace", "price" : "79", "description" : "The Summer Palace, is a vast ensemble of lakes, gardens and palaces in Beijing, China. It was an imperial garden in Qing Dynasty. Mainly dominated by Longevity Hill and Kunming Lake, it covers an expanse of 2.9 square kilometres (1.1 sq mi), three-quarters of which is water.", "image" : "summer_palace"],
                ["name" : "National Art Museum", "price" : "3", "description" : "Chinese art developed almost completely separately from that in the west and, considering its age, imported techniques and mediums have only become popular relatively recently. NAMOC was opened by Chairman Mao in 1963 to showcase modern Chinese art and now sports a great collection of traditional Chinese ink and wash paintings as well as the sort of socialist-themed pieces you would expect at a museum set up by the communist party. But don't make the mistake of thinking that this museum is stuffy; though the exhibited works are hardly likely to contain anything too controversial, there's a smattering of contemporary pieces that have sent international collectors into a tizz.", "image" : "national_art_museum_of_china"],
                ["name" : "Forbidden City", "price" : "6", "description" : "The Forbidden City in Beijing was constructed in the late fifteenth century and was initially known as the Palace Museum. Today, the city consists of over 9,000 rooms for accommodation and is spread over a huge area of 250 acres. The significance of the attraction in Beijing arises from the fact that in the ancient times, this place served as a home to the emperors and their families and was also the centre for holding ceremonial processions and conducting political agendas. What is worthy of attention at this landmark in Beijing is the traditional Chinese architecture that is an exemplary display of cultural and traditional developments adopted from the East Asia region. Today, this place is a declared World Heritage site for the largest collection of preserved wooden structures in the world.", "image" : "forbidden_city"]
            ],
            "outdoors" : [
                ["name" : "Beijing Zoo", "price" : "3", "description" : "Beijing Zoo can be visited under a guided tour that will be perfect to explore the area in a systematic manner. You can spot a number of animals in this zoo including bears, wild cats and even pandas. Beijing Zoo is close to the metro station that makes it easily accessible. You will be amazed after visiting this space as there are some rare species of animals that will surely stun your mind. Make sure you do not touch any of the enclosures. Feeding the animals is strictly prohibited at Beijing Zoo. The managing staff at this zoo is not that active. Kids would love the visit to Beijing Zoo as it will help them learn about wildlife.", "image" : "beijing_zoo"],
                ["name" : "Olympic Park", "price" : "0", "description" : "Olympic Park can be visited easily as it is located in the Chaoyang District. This park is very attractive in terms of its setup. You can come here with your friends and family to spend a lovely time surrounded by nature. Olympic Park is located close to the main stadium and is also near to Bird’s Nest and Water Cube. At night, the whole area is well lit to offer a lovely view. There is a wall present close to Olympic Park that includes the names of the 2008 Olympic winners. Make sure you avoid your visit on the weekends as the place is too crowded. Subway is the best way to reach Olympic Park without any hassle", "image" : "olympic_park"],
                ["name" : "Beijing Botanical Garden", "price" : "1", "description" : "Beijing Botanical Garden should be visited if you are a nature lover. There are a number of flower varieties present in this area that will surely impress your eyes. The early spring season is the perfect time to visit Beijing Botanical Garden. The air in this area is very fresh due to the presence of numerous plants and trees. The rose garden inside Beijing Botanical Garden is the most famous spot for the public. There are also lakes present inside Beijing Botanical Garden which makes the place worth visiting. There are even greenhouse chambers present that will help you learn about plant growth and preservation. The staff at Beijing Botanical Garden is very active.", "image" : "beijing_botanical_garden"]
            ],
            "nightlife" : [
                ["name" : "Vics NIGHTCLUB", "price" : "10", "description" : "The hottest and the hippest nightlife destination in Beijing, Vics NIGHTCLUB includes a sports bar, a restaurant, and a club. Swoon over the enigmatic vibe and the excellence of music showcased here. The talented DJs play a mix of pop, R&B, hip-hop, reggae and soul. The colorful lights, lanterns, and furniture, add to the ornate interiors of the restaurant. The staff is cordial and gives you a hospitable treatment. From food to music to décor, everything is inviting about this place. Their wide range of cocktails, mocktails, and other beverages spoil you for choice. Vics nightclub has a huge computer screen that lets VJs showcase their talent. The sound system is pleasingly loud, a huge relief from the ear deafening volumes of the usual clubs. So, trigger up your party rave and head to Vics Club.", "image" : "vics_nightclub"],
                ["name" : "Modern Tea House Lounge", "price" : "28", "description" : "Located at South Sanlitun, Long Jing Modern Tea House & Cocktail Lounge is the place to be. A teahouse by day and a cocktail bar by night, it is an excellent venue to drop in with your friends. If the brewed tea doesn’t get you going, gulp down one or two of their signature cocktails. Nicely decorated with a minimalistic approach, well-balanced sound system, and expert lighting makes it an ideal place to enjoy a cocktail. The staff employed is friendly and serve you with a smile. They have a simple concept – brew tea, mix booze, get drunk. The place has comfortable sofas and armchairs and low-lying tables. When here, the must-try cocktail is the Longjing. A blast of flavors evolve sip after sip. Another star on the drinks menu is a cocktail named ‘Rich’.", "image" : "modern_tea_house_lounge"],
                ["name" : "Slow Boat Brewery Taproom", "price" : "12", "description" : "Well-hidden down under a residential street, Slow Boat Brewery Taproom is home the largest selection of beer in Beijing. An amazing place to catch up with old friends or meet new people, it is a cool little bar with a selection of fifteen fine beer brands on tap. The hutong atmosphere and the lively vibe add to the charm of the place. This place also serves refreshments, limited but lip-smacking. When here, tuck into their Fry Burger stuffed with fries and handmade sodas. Talking about beer, there is a long list of North-American and core beer here. The Monkeys First IPA and Captain’s Pale Ale are highly recommended. The staff employed is extremely courteous and prices are reasonable. Slow Boat Brewery Taproom is the ultimate destination for your beer cravings in Beijing.", "image" : "slow_boat_brewery_taproom"]
            ]
        ],
        "Barcelona" : [
            "cultural" : [
                ["name" : "La Sagrada Familia", "price" : "18", "description" : "The Basílica i Temple Expiatori de la Sagrada Família is a large unfinished Roman Catholic church in Barcelona, designed by Catalan architect Antoni Gaudí.", "image" : ""],
                ["name" : "FC Barcelona museum & Camp Nou stadium", "price" : "28", "description" : "Home of Barcelona football team. If there are no games during your visit, then book the stadium and museum tour. TICKETS Camp Nou Experience The Camp Nou stadium and FCB museum are among the most popular attractions in Barcelona attracting millions of visitors a year. Camp Nou also has the one of the largest Nike stores in Europe packed with Barca merchandise. ", "image" : ""],
                ["name" : "Picasso Museum", "price" : "13", "description" : "The Picasso Museum is Barcelona's most famous museum. Pablo Picasso was born in Malaga in the south of Spain, but the Picasso family moved to Barcelona in 1895 and Picasso lived here until 1904. Picasso's father was an art teacher and although as a child Pablo Picasso already studied art in Malaga, it was in Barcelona that he spent his formative years. The Picasso museum has free admission for everyone on first Sunday of month all day and free every Thursday after 6pm. ", "image" : ""]
            ],
            "outdoors" : [
               ["name" : "The Magic Fountain of Montjuic", "price" : "0", "description" : "The Magic Fountain is a 'must see' Barcelona attraction. You have never seen a fountain like this. It really does feel magic to experience the beautiful show of water, light and music. The Magic fountain was built in 1929 as one of the main attractions for the Barcelona World Fair and the Font Magica is still one of the most famous spots in Barcelona with an estimated 2.5 million visitors annually. There are evening water and light shows in the winter on Friday and Saturdays only. In the summer the evening light and music show are from Thursday to Sunday. Admission is free all year.", "image" : ""],
                ["name" : "Las Ramblas street", "price" : "0", "description" : "Also called Las Ramblas because it consists of diffferent sections. The Spanish poet Federico García Lorca said 'It is the only street in the world which I wish would never end' and it almost doesn't because it now continues into Port Vell marina. La Rambla starts at central square Plaza Catalunya and ends at the Columbus monument at the Port Vell marina. La Rambla it is not a spectacular attraction in any way, but very pleasant to stroll down and feel the human heartbeat of Barcelona.", "image" : ""],
                ["name" : "Barrio Gotico", "price" : "0", "description" : "The gothic quarter is the medieval city of Barcelona. It grew around the ancient Roman town of Barcino which is Barcelona's oldest area. The gothic part of the city has many beautiful churches, plazas, markets and museums and you can see parts of the old Roman walls. If you visit the Barcelona history musuem Museu d'Història de la Ciutat you can see remains of Roman Barcino houses and streets under the museum. ", "image" : ""]
            ],
            "nightlife" : [
                ["name" : "Sala Razzmatazz", "price" : "18", "description" : " Expect a social and non-pretentious atmosphere. Located in Barcelona’s industrial urban district of Poble Nou, don’t be surprised if you lose all your friends (and maybe your mind) within the labyrinth of rooms. On a weekend, access the entire complex made up of industrial factories on different levels, each with a separate DJ. Established in the year 2000, Sala Razzmatazz was the first club in Spain to schedule five different spaces every day of the week, and is consistently ranked by the  DJ mag list of top 100 clubs.", "image" : ""],
                ["name" : "Pacha Barcelona", "price" : "24", "description" : "Ibiza style clubbing in the purest form. Visitors are greeted by a sleek white interior and a stunning view over the beach. Located near the Barceloneta Beach, the club attracts a crowd that is international with a both smart and casual atmosphere. This club has a bit more of an edge than its Port Olimpic neighbors, particularly on Sundays presented by FACT.", "image" : ""],
                ["name" : "La Terrrazza", "price" : "18", "description" : "This place has a fresh, happy vibe, fitting of the title “Atmospherical Fun Club”.  Tell your friends back home you’re going to an open-air party at a night club in a castle and watch their jaws drop. The way inside is through the gates of Poble Espanyol, a mini-village atop Montjuic whose streets were modeled from the various styles of architecture in each region of Spain.", "image" : ""]
            ]
        ],
        "Dubai" : [
            "cultural" : [
                ["name" : "Burj Khalifa", "price" : "27", "description" : "Standing tall at 828 metres in Downtown Dubai, the sky-piercing Burj Khalifa is the tallest man-made structure in the world. The glorious tower is one of the most prominent attractions in all of the Middle-East. It displays exceptional work of art and it is not without reason that it has been called the Jewel of Dubai. Climb up to the 124th floor on the observation deck, At The Top, for an uninterrupted view of the city’s skyline and beyond.", "image" : ""],
                ["name" : "Al Bastakiya", "price" : "10", "description" : "Also known as the Al Fahidi Historic District of Dubai, Al Bastakiya is one of the oldest and traditional Emirati residential areas in Bur Dubai. Constructed in the 1690s, Al Bastakiya gives you interesting insights into the rich cultural heritage of Dubai. The historic site offers a good break from the modernism and technological advancement that Dubai stands for.", "image" : ""],
                ["name" : "Bastakia Quarter", "price" : "0", "description" : "A visit to Bastakia Quarter will acquaint you with many culturally important sights of Dubai. Some of them are Al Fahidi Fort, Dubai Museum, Sheikh Mohammed Centre for Cultural Understanding and many other buildings that were built in the 1780s. Bastakia Quarter is basically a historic walking area and a great place to know all about the traditional Dubai. It also houses Dubai’s oldest commercial art gallery, Majlis Gallery. ", "image" : ""]
            ],
            "outdoors" : [
                ["name" : "Al Mamzar Park", "price" : "2", "description" : "A pretty and landscaped garden, Al Mamzar Park spreads over 106 hectares. It is situated on an inlet which lends it white sandy beaches and many more beautiful sights. There is also a swimming pool, BBQ sites, food kiosks and plenty of open spaces which the kids will especially love. ", "image" : ""],
                ["name" : "Ras Al Khor ", "price" : "0", "description" : "Extremely popular for the large number of migratory birds that come here, Ras Al Khor is a beautiful nature reserve and wetland in Dubai. Pink flamingos are the highlight of any visit to this sanctuary in winters. Located at the mouth of Dubai Creek, Ras Al Khor is the place to be for bird watchers and nature lovers. Don’t miss the bird feeding sessions here which are held at 9:15 and 16:15 pm every day.", "image" : ""],
                ["name" : "Dubai Desert Conservation Centre", "price" : "0", "description" : "With its aim to protect the biodiversity of the Arabian deserts, the Dubai Desert Conservation Centre is a natural habitat for the flora and fauna of the region. In addition to this, it also has many exotic migratory birds visiting it during different times of the year. Get up close and personal with the falcons and enjoy camel treks, horse riding, archery and sandboarding among many other activities that the Conservation Centre offers.", "image" : ""]
            ],
            "nightlife" : [
                ["name" : "Copacabana", "price" : "13", "description" : "Named possibly after the 70’s Barry Manilow hit, the Copa Cabbana has become popular among the increasingly large young and trendy crowd in Dubai. Sandy floors and Bamboo Railings give it quite an interesting look unique from many rivalling establishments. The club is also renowned for having fantastic snacks. The entry fee is 50 Dhs (€10) and you must be over 25 to enter in order to keep out those who are too junior.", "image" : ""]
            ]
        ],
        "Honolulu" : [
            "cultural" : [
                ["name" : "Polynesian Cultural Center ", "price" : "62", "description" : "The Polynesian Cultural Center features distinct exhibition areas covering the islands of Hawaii, Aotearoa (New Zealand), Fiji, Samoa, Tahiti, Tonga, and Rapa Nui (Easter island). Book full-day admission tickets for full access to the site, a dinner experience with a luau option, and the thrilling “Ha: Breath of Life” night show, or half-day afternoon tickets for access to one island village, dinner, and the night show", "image" : ""],
                ["name" : "Hanauma Bay", "price" : "7.50", "description" : "Formed within a volcanic cone, today Hanauma Bay offers a pristine marine ecosystem after the City and County of Honolulu laid out a plan in 1990 to restore the “curved bay,” after years of use from the millions of visitors who visit and love to snorkel Hanauma Bay. Voted the Best Beach in the United States for 2016 our volunteers have a booth located on the beach level to help visitors learn about conservation of the reef and the types of fish that live there. ", "image" : ""]
            ],
            "outdoors" : [
                ["name" : "Pearl Harbor", "price" : "22", "description" : "Arguably one of the most significant World War II sites on the planet, Hawaii's Pearl Harbor—once a tranquil oyster farming bay—hurtled the United States into World War II combat on the Pacific Ocean. Today, the central Oahu port features several attractions that memorialize the 2,403 lives lost to Japan's devastating bombings of American ships and planes in 1941.", "image" : ""],
                ["name" : "North Shore", "price" : "0", "description" : "Surfing is king on Oahu’s North Shore, where summer’s placid snorkeling spots are transformed into pounding 40-foot (12-meter) waves come winter. On land you’ll find a peaceful respite from hectic Honolulu, with scenic waterfall hikes, sleepy farms selling tropical fruit, and food trucks doling out garlic shrimp.", "image" : ""],
                ["name" : "Lanikai Beach", "price" : "0", "description" : "Nevertheless, Lanikai is the perfect place for a comfortable chair, a good book, and the view looking out at the Mokulua islands graces the cover of many Oahu postcards. The white sand of Lanikai is the perfect place to spend the morning, or, if you happen to time it right, watch the full moon rise over the eastern horizon and as illuminates the cliffs of the Ko’olau Mountains.", "image" : ""]
            ],
            "nightlife" : [
                ["name" : "District Nightclub", "price" : "20", "description" : "The District Nightclub is Honolulu, Hawaii's Newest & Best Night Life Experience. Located several minutes from Waikiki and across of Ala Moana Shopping Center. The 3,400 square foot nightclub showcases a specially-designed 23-foot DJ booth, VIP lounge, 12 private tables and will take service to new heights . ", "image" : ""],
                ["name" : "Ginza Nightclub", "price" : "10", "description" : "The Ginza Nightclub is Honolulu's Exclusive After Party Destination. Located one block from Ala Moana Shopping Center in the middle of Honolulu's most lively nightlife scene.", "image" : ""]
            ]
        ],
        "London" : [
            "cultural" : [
                ["name" : "Warner Bros Studio Tour", "price" : "100", "description" : "Have a magical day out with a behind-the-scenes tour of the Harry Potter films at Warner Bros. Studio Tour London  – The Making of Harry Potter. See first-hand the sets, costumes, and props used in all the Harry Potter films, and step inside some of the films' locations including the Great Hall, Dumbledore's office and Hagrid's hut. It's the ultimate Harry Potter experience!", "image" : ""],
                ["name" : "Buckingham Palace", "price" : "33", "description" : "Visit the official London residence of the Queen during the Buckingham Palace summer opening. Explore the extravagant State Rooms and don't miss this year's special exhibition, celebrating the 70th birthday of the Prince of Wales. In 2018, Buckingham Palace is open to visitors from 21 July until 30 September.", "image" : ""],
                ["name" : "Tower of London", "price" : "36", "description" : "Take a tour with one of the Yeoman Warders around the Tower of London, one of the world's most famous buildings. Discover its 900-year history as a royal palace, prison and place of execution, arsenal, jewel house and zoo! Gaze up at the White Tower, tiptoe through a medieval king's bedchamber and marvel at the Crown Jewels", "image" : ""]
            ],
            "outdoors" : [
                ["name" : "Kensington Palace", "price" : "23", "description" : "Kensington Palace offers a glimpse into the lives of its past royal residents. Discover stories from Queen Victoria's life in the Victoria Revealed exhibition; master courtly games in the King's State Apartments; glimpse a modern princess in an exhibition of Diana's dresses; and uncover the secrets of a fragile dynasty in the Queen's State Apartments.", "image" : ""],
                ["name" : "The View from The Shard", "price" : "33", "description" : "Rise high above London and see the city's iconic skyline from a unique perspective, with views stretching up to 40 miles (64km). Spot the likes of the Coca-Cola London Eye, St Paul's Cathedral and Wembley Stadium from The View from The Shard's observation deck, which sits 800ft (244m) up western Europe's tallest building.", "image" : ""]
            ],
            "nightlife" : [
                ["name" : "Camden Rocks Club", "price" : "7", "description" : "Vibrant as always, guests to the Camden Rocks Club Night in North London night out can enjoy drinks for only £3 and special performances from the likes of Gallows and FVK. With entry costing only £5 and a frequent host of surprise musical appearances, Underworld has become a favourite amongst the city's rock lovers and continues to draw in crowds from all over come Saturday night.  ", "image" : ""],
                ["name" : "Sway", "price" : "0", "description" : "Sway by Covent Garden has three bars (Cream, Crystal and Milk), a nightclub and a restaurant under one roof. Come for late-night drinking and dancing and you won't be disappointed by their cool decor. The music varies in the different rooms but expect great party music, club classics and chart as well as some boogie-woogie in the Groovy Wonderland.", "image" : ""],
                ["name" : "Tiger Tiger London", "price" : "0", "description" : "This is one of the most famous London night clubs for its every-night party spirit! Slap bang in the heart of London, Tiger Tiger attracts a mixed crowd who all come to party hard. Great happy hours and party tunes whip up a fun night out.", "image" : ""]
            ]
        ],
        "Moscow" : [
            "cultural" : [
                ["name" : "The Kremlin", "price" : "0", "description" : "The Moscow Kremlin is one of the most ancient parts of the city and symbolises the whole of Russia. It is both a cultural sight, as well as the centre of the Russian state, and the residence of the President of Russia. The Kremlin is steeped in history. In 1990, the Moscow Kremlin and the Red Square were included into the list of UNESCO worldwide heritage.", "image" : ""],
                ["name" : "Bolshoi Theatre", "price" : "20", "description" : "The Bolshoi Theatre is the most famous theatre in Moscow. The theatre shows around 3-4 different operas and 2-3 ballets each year. The focus is on classical masterpieces from composers such as Mozart, Verdi, Wagner, and Tchaikovsky. Russian ballet is world famous and is an important part of the Russian culture.", "image" : ""],
                ["name" : "", "price" : "", "description" : "", "image" : ""]
            ],
            "outdoors" : [
                ["name" : "GUM Department Store", "price" : "0", "description" : "The GUM is a huge shopping centre, one of the largest in Europe. It is the most famous place to shop in Moscow, but it is also known for its architecture. It is situated on Red Square and the first part of it was built in 1812, under Alexander I. The shop itself has a luxurious style, selling brands such as Louis Vuitton, Dior, Hugo Boss, Burberry etc. There are also many cafes and restaurants.", "image" : ""],
                ["name" : "The Red Square", "price" : "0", "description" : "Red Square remains, as it has been for centuries, the heart and soul of Russia. Few places in the world bear the weight of history to the extent that Moscow's central square does. From the 16th Century St. Basil's Cathedral - one of the most famous pieces of architecture in the world - to the constructivist pyramid of Lenin's Mausoleum, Red Square is rich in symbols of Russia's turbulent and intriguing past.", "image" : ""]
            ],
            "nightlife" : [
                ["name" : "Solyanka Club", "price" : "10", "description" : "The Solyanka Club  was opened back in 2007 and has become the Mecca of the City’s club scene. It’s a little pretentious in here and is predominately frequented by artistic types and fashionistas.  Their audience tends to be young and their best nights are on Friday’s and Saturday’s.  The queue can be quite long on weekends so try to be patient. Their live DJ’s play notorious Dance and House tracks.", "image" : ""],
                ["name" : "Krysha Mira Club", "price" : "24", "description" : "Krysha Mira is an opulent club which seems to draw in Moscow’s opulent club creatures. They play Techno and House music and Friday’s are by far their busiest nights. Drinks are remarkably costly with a shot of vodka costing you somewhere between 10 and 15 Euro’s. Unless you are wearing designer outfits and speaking English then you will struggle to enter this exclusive venue.", "image" : ""]
            ]
        ],
        "Munich" : [
            "cultural" : [
                ["name" : "The Deutsches Museum", "price" : "13", "description" : "The Deutsches Museum in Munich, Germany, is the world's largest museum of science and technology, with about 28,000 exhibited objects from 50 fields of science and technology. It receives about 1.5 million visitors per year.", "image" : ""],
                ["name" : "Old Picture Gallery", "price" : "5", "description" : "Alte Pinakothek is known as one of the most popular galleries around the world, as well as one of the richest treasuries with priceless paintings. This gallery exhibits works of the masters of the Middle Ages, dating from a period starting from the middle of the 18th century. There is a collection of 700 paintings, located in 19 halls and 49-year-offices.  ", "image" : ""],
                ["name" : "BMW World", "price" : "12", "description" : "BMW Welt is a multi-use exhibition center located in Munich, Germany used for meetings and promotional events, and where buyers take delivery of BMW vehicles.", "image" : ""]
            ],
            "outdoors" : [
                ["name" : "Nymphenburg Palace", "price" : "14", "description" : "The Nymphenburg Palace, Castle of the Nymph, is a Baroque palace in Munich, Bavaria, southern Germany. The palace was the main summer residence of the former rulers of Bavaria of the House of Wittelsbach.", "image" : ""],
                ["name" : "English Garden", "price" : "0", "description" : "Located in the centre of the city, the English Garden (der Englische Garten) is a large park (3.73 square kilometres), open throughout the year, that offers mostly hard-dirt paths for walking and running as well as lakes. Visitors can partake in horse riding, boating, and even surfing at the Eisbachwelle in front of the Haus der Kunst", "image" : ""],
                ["name" : "Olympiapark", "price" : "0", "description" : "The venue of the 1972 Olympics, the Olympiapark is now a hub for indoor and outdoor activities. As well as lakes with boat hire and excellent paths for running, nordic walking and cycling, the site offers indoor facilities for tennis, ice skating, inline skating, watersports, football and working out. The park also has a mini-golf course.", "image" : ""]
            ],
            "nightlife" : [
                ["name" : "Feierwerk", "price" : "15", "description" : "In the Feierwerk complex you'll find some of the best venues for live music in the city - the Orangehouse, Sunny Red, Kranhalle and Hansa 39. Get your fill of local and international hip hop, punk, hardcore, metal, electronic, ska and indie bands. In the summer, the club expands events into on-site tents. Almost every night of the year there are events scheduled in at least two of the Feierwerk locations and usually two very different genres.", "image" : ""],
                ["name" : "Substanz", "price" : "18", "description" : "Synonymous with creative expression, Substanz is in an artistic section of town. As well as a program of live music and DJ's, the club hosts the Munich Poetry Slam and the English Comedy Club. Easy to find, the bar is ten minutes from Marienplatz on the U3/U6 subway lines. Occasionally, the bar shows German sports, too.", "image" : ""],
                ["name" : "Harpers and Queens", "price" : "0", "description" : "Chill in a comfortable lounge setting. On one of the main shopping streets, the bar is easy to reach by subway or walking from Marienplatz. Mondays feature all-night happy hour; choose from a large selection of cocktails while sitting on built-in red couches. Though elegant, the atmosphere is conducive to conversation.", "image" : ""]
            ]
        ],
        "New York City" : [
            "cultural" : [
                ["name" : "Statue of Liberty", "price" : "18", "description" : "The Statue of Liberty was France's gift to America. Built in 1886, it remains a famous world symbol of freedom and one of the greatest American icons. It is one of the world's largest statues, standing just under 152 feet tall from the base to the torch, and weighing approximately 450,000 pounds.", "image" : ""],
                ["name" : "Metropolitan Museum of Art", "price" : "25", "description" : "The Metropolitan Museum of Art, or the Met, as it is commonly known, was founded in 1870, and is one of the most famous museums in the United States. The permanent collection of The Met contains more than two million works of art, spanning a period of 5,000 years. Although the museum has three sites, the centerpiece is The Met Fifth Avenue.", "image" : ""],
                ["name" : "Rockefeller Center", "price" : "0", "description" : "Rockefeller Center is a vast entertainment and shopping complex in the middle of Manhattan, and home to NBC-TV and radio, and other media. The centerpiece of the complex is the 70-storey 30 Rockefeller Plaza, an Art Deco skyscraper that offers awesome views over Manhattan from the famous Top of the Rock Observation Deck. ", "image" : ""]
            ],
            "outdoors" : [
                ["name" : "Central Park", "price" : "0", "description" : "A walk, peddle, or carriage ride through the crisscrossing pathways of Central Park is a must-do on anyone's New York City itinerary. In winter, you can even lace up your skates and glide across Wollman Rink. This huge park in the city center, a half-mile wide and 2.5 miles long, is one of the things that makes New York such a beautiful and livable city. ", "image" : ""],
                ["name" : "Broadway", "price" : "100", "description" : "Attending a Broadway show is one of the highlights of a visit to New York City. Considered the pinnacle of American theater, this is the place to see the latest shows and the long-running classics. Broadway usually refers simply to Broadway theater, which encompasses a large number of theater venues in the Theater District and along the street of Broadway. For the most popular shows, tickets should be purchased well in advance.", "image" : ""],
                ["name" : "Empire State Building", "price" : "0", "description" : "The Empire State Building is one of New York's most famous landmark buildings. The 381-meter-tall, 102-storey building was the tallest in the world until the 1 World Trade Center tower rose higher, 41 years later. Topped with a mooring mast for airships, the Empire State Building immediately became a landmark and a symbol for NYC when it opened in 1931.", "image" : ""]
            ],
            "nightlife" : [
                ["name" : "Eating It", "price" : "8", "description" : "For several years, this Monday night series has provided an environment where lesser known comedians as well as established jokesters like Jon Stewart and Saturday Night alums try out their new material.", "image" : ""],
                ["name" : "Arthur's Tavern", "price" : "0", "description" : "or more than 65 years, this legendary live-music venue has been home to performances ranging from Dixieland jazz to Chicago blues. There's no cover and the two-drink minimum is rarely enforced since it's impossible to keep track of who's who in the packed crowd.", "image" : ""],
                ["name" : "Cheeta Club", "price" : "10", "description" : "Decent star watching and decadent atmosphere make this a great club for dancing or lounging around", "image" : ""]
            ]
        ],
        "Paris" : [
            "cultural" : [
                ["name" : "Arc de Triomphe", "price" : "0", "description" : "The Arc de Triomphe is arguably one of the most photographed landmarks in Paris. Climb up to the viewing platform for spectacular panoramas over Paris and see the Tomb of the Unknown Solider underneath, with the intricate designs and engravings that make up the pillars of the arch.", "image" : ""],
                ["name" : "Louvre Museum", "price" : "18", "description" : "One of the most famous art galleries is the Louvre Museum, home to the iconic Mona Lisa. This historic building dates back to the 12th century when it was originally a fortress, before it was a palace in the 16th century, later becoming a museum in 1793. You can’t miss the iconic glass pyramid in the courtyard in front. ", "image" : ""],
                ["name" : "Notre Dame Cathedral", "price" : "12", "description" : "The impressive Notre Dame Cathedral sits on the Île de la Cité and is considered one of the best examples of French Gothic architecture in the world – not to mention its huge scale means it’s also one of the largest, too. Built in the mid-14th century, with its gargoyles and stained glass windows added over time, it’s now one of the most recognised churches in the world – and thanks to Victor Hugo’s The Hunchback of Notre Dame, it’s a favourite of both adults and kids alike.", "image" : ""]
            ],
            "outdoors" : [
                ["name" : "Bateaux Parisiens River Cruise", "price" : "18", "description" : "Get a unique perspective on Paris and take a majestic trip along the Seine River on the Bateaux Parisiens to discover the City of Lights from the water. Glide past the Notre Dame Cathedral and under the famous Pont Neuf, to name a few, starting your trip at the Eiffel Tower, or Notre Dame itself.", "image" : ""],
                ["name" : "Eiffel Tower", "price" : "20", "description" : "When Gustave Eiffel’s company built Paris’ most recognizable monument for the 1889 World’s Fair, many regarded the massive iron structure with skepticism. Today, the Eiffel Tower, which continues to serve an important role in television and radio broadcasts, is considered an architectural wonder and attracts more visitors than any other paid tourist attraction in the world.", "image" : ""]
            ],
            "nightlife" : [
                //["name" : "", "price" : "", "description" : "", "image" : ""],
            ]
        ],
        "Seattle" : [
            "cultural" : [
                ["name" : "Space Needle and Chihuly Garden and Glass ", "price" : "44", "description" : "Travel to the top of the Space Needle's 520 ft. observation deck for unparalleled views of downtown Seattle, Mt. Rainier, and the Puget Sound, plus hands-on digital experiences and FREE digital souvenir photos.  Right next to the Space Needle, immerse yourself in a world where curiosity, creativity and color come to life at Chihuly Garden and Glass. Throughout the Galleries, ever-changing Garden and signature Glasshouse, where you’ll be inspired by artist Dale Chihuly’s innovation and passion.", "image" : ""],
                ["name" : "Boeing Factory", "price" : "88", "description" : "Get a behind-the-scenes look at airplane design and manufacturing on a 4.5-hour Boeing factory tour that includes the Future of Flight Aviation Center, and round-trip transport from Seattle and SeaTac hotels. Watch the factory floor and flight line from above, get a virtual tour of a 787 flight deck, then use a simulator to design and test your own airplane.", "image" : ""],
                ["name" : "Woodland Park Zoo", "price" : "15", "description" : "A short distance from downtown Seattle, Woodland Park Zoo is an urban oasis that sparks delight, discovery, and unforgettable memories in a botanical setting that connects visitors with nature to learn, care and act on behalf of wildlife.  Explore 92-acres teeming with tigers, penguins, gorillas and 300+ animal species living in spacious, naturalistic settings. Be inspired and discover what action you can take to help save wildlife.", "image" : ""]
            ],
            "outdoors" : [
                ["name" : "Pike Place Market", "price" : "0", "description" : "With more than a century of history, Pike Place Market is the oldest continuously operating farmers market in the country and one of Seattle’s most popular draws. The market lures visitors and locals alike (we’re talking 10 million people per year) with its farm-fresh produce, butcher-paper clad bouquets, abundance of shops, restaurants, and bars—not to mention some of the best people-watching in the city", "image" : ""],
                ["name" : "Mount Rainier", "price" : "0", "description" : "Ascending to 14,410 feet above sea level, Mount Rainier stands as an icon in the Washington landscape. An active volcano, Mount Rainier is the most glaciated peak in the contiguous U.S.A., spawning six major rivers. Subalpine wildflower meadows ring the icy volcano while ancient forest cloaks Mount Rainier’s lower slopes. Wildlife abounds in the park’s ecosystems. A lifetime of discovery awaits.", "image" : ""]
            ],
            "nightlife" : [
                ["name" : "Chop Suey", "price" : "5", "description" : "Following an ownership changeover, Chop Suey has gone from oddly-Asian-themed bar and secret live-music powerhouse underdog to still confusingly decorated music venue that now has a side bar and second stage in its Den. It also has pinball machines, a mostly functioning (as opposed to previously never functioning) photo booth, and a kitchen window from which to buy chicken and other fried delights.", "image" : ""],
                ["name" : "Trinity Nightclub", "price" : "0", "description" : "Located at 107 Occidental Ave, Seattle WA 98104 in Seattle’s historic Pioneer Square Neighborhood. Trinity Nightclub is a uniquely original, two level space, housing three separate rooms and a large private VIP room, each with it’s own  distinctive theme and décor. Trinity features a full lounge, state of the art sound and lighting and two spacious dance floors. Trinity is 21+ at all times.", "image" : ""]
            ]
        ]
    ]
    
    var culturalActivities: [[String : String]]
    var outdoorsActivities: [[String : String]]
    var nightlifeActivities: [[String : String]]
    
    init(cityName: String) {
        self.culturalActivities = Activities.activitiesData[cityName]!["cultural"]!
        self.outdoorsActivities = Activities.activitiesData[cityName]!["outdoors"]!
        self.nightlifeActivities = Activities.activitiesData[cityName]!["nightlife"]!
    }
}
