//
//  Activities.swift
//  travely
//
//  Created by Alexandra Leonidova on 3/18/18.
//  Copyright © 2018 University of San Diego. All rights reserved.
//

import Foundation

class Activities{
    //data
    static var activitiesData = [
        "San Diego" : [
            "cultural" : [
                ["name" : "Old Town San Diego State Historic Park", "price" : "0", "description" : "Old Town San Diego State Historic Park presents the opportunity to experience the history of early San Diego by providing a connection to the past. Learn about life in the Mexican and early American periods of 1821 to 1872. Even today, life moves more slowly in this part of San Diego, where the hustle and bustle is balanced with history and fiestas. Visitors are offered a glimpse into yesteryear, as converging cultures transformed San Diego from a Mexican pueblo to an American settlement. San Diego became California's first Spanish settlement when a mission and fort were established here in 1769. Later, it passed into the hands of the newly made Mexican government before gaining statehood in the United States after the Mexican-American War."],
                ["name" : "USS Midway Museum", "price" : "21", "description" : "The USS Midway Museum is a maritime museum located in downtown San Diego, California at Navy Pier. The museum consists of the aircraft carrier Midway. The ship houses an extensive collection of aircraft, many of which were built in Southern California"],
                ["name" : "Balboa Park", "price" : "0", "description" : "San Diego is home to the nation’s largest urban cultural park with 15 major museums, renowned performing arts venues, beautiful gardens and the San Diego Zoo. Exploring the park grounds is a free and lovely thing to do, especially if you can catch a special event like a free Spreckels organ performance."]
            ],
            "outdoors" : [
                ["name" : "Potato Chip Rock Hike Free", "price" : "0", "description" : "The Mount Woodson hike leading to potato chip rock isn’t exactly for beginners as it’s rocky and uphill but the epic photo at Potato Chip Rock is one to frame. This 8-mile hike is in Poway."],
                ["name" : "Kayak Sea Caves", "price" : "70", "description" : "Off the coast of La Jolla Shores is a marine life-rich underwater park lined by seven sea caves. A variety of kayaking tours take you by the caves (and inside depending on conditions) while telling stories about how they were used during prohibition to smuggle booze into town. Along the way, you’ll no-doubt see leopard sharks, orange Garibaldi (California’s state fish), and friendly sea lions."],
                ["name" : "La Jolla Seals And Sea Lions", "price" : "0", "description" : "La Jolla’s seals and sea lions are used to people and you can get quite close to them, however, a respectful distance is encouraged. It’s easy to fill up a flash card with photos of them lazing along the coastline, often snuggled up against one another. Adults love this just as much as kids do. See my guide for how best to see the La Jolla seals and sea lions."]
            ],
            "nightlife" : [
                ["name" : "Noble Experiment", "price" : "10", "description" : "Named after the “Noble Experiment” of Prohibition, this speakeasy is concealed inside a restaurant in the Gaslamp Quarter called Neighborhood, located at 777 G. Street. The Noble Experiment is the hardest of the San Diego speakeasies to find, since the hidden door is disguised as a wall of beer kegs close to the bathrooms. Simply push on the right side of the wall of beer kegs and you can enter the bar, with a red neon sign greeting you and a series of ornate brass skulls adorning the walls. Look around and you will notice the glowing chandelier, intricate paintings on the ceiling, white booths, and an overall Gothic style with dim red lighting to really set the mood of secrecy. The Noble Experiment is known for its excellent crew of mixologists, who can create a classy cocktail suited to your particular taste buds if you simply order the “Bartender’s Choice.” The bar pays homage to historical accuracy by only serving pre-Prohibition liquor, so don’t expect to find any vodka here. The average price for a cocktail is twelve dollars, but the bartenders take their time to produce only the best drinks, and they are definitely worth the price."],
                ["name" : "Sunset Cruise", "price" : "39", "description" : """
                    At Cruise San Diego, our Sunset Cruise lets you experience a “sunset” side of Mission Bay that very few get to see, with our unique vessel designed especially for bay cruises, relaxing atmosphere, and awe-inspiring Pacific sunsets you are sure to enjoy this boat ride like no other.
                    This tour was designed specifically for anyone seeking a personal touch to an average sunset cruise.
                    Explore the pristine waters of our Mission Bay lagoon on our year round cruise inside this beautiful bay. You will enjoy a great selection of music and alcoholic beverages, allowing you to experience an intimate yet laid-back mood unlike any other sunset cruise in Mission Bay or San Diego.
                    Whether you are looking for a romantic outing, or a relaxing way to enjoy the evening sunset, our sunset cruise will satisfy any occasion.
                    """],
                ["name" : "Sevilla Night Club", "price" : "5", "description" : """
                    One of the most Popular & Longest running Nightclubs in San Diego's Gaslamp Quarter, Sevilla Nightclub was launched in 1987 and has been drawing fans of the many forms of Latin, Spanish Music & Dance ever since & has remained the Top Destination for San Diego Nightlife.
                    Sevilla Nightclub has an Intimate Ambiance, Roomy Dance Floor, VIP Bottle Service Amenities, a Plush Lounge area, and a Full Tapas Menu to choose from, delivering a unique atmosphere and the best in San Diego in Latin & Open Format DJs, Salsa, Bachata, & Merengue Dance Instructors, and Live Bands. Early arrival & VIP Bottle Service is always recommended, as there are often long lines outside.
                    """]
            ]
        ],
        "Rome" : [
            "cultural" : [
                ["name" : "Colosseum", "price" : "15", "description" : "The Roman Colosseum is a testament to the architectural skills of the ancient Roman people and offers insight into the culture that celebrated the gladiator games at this huge entertainment arena. The first bloody fight ensued in A.D. 82, starting a tradition of battles between men and beasts in a public forum with crowds reaching 50,000. Outside of the Colosseum, look out for the photo opportunity beneath the Arch of Constantine, which was built in 315 to commemorate the victory of Constantine over Marcus Aurelius Valerius Maxentius."],
                ["name" : "Vatican", "price" : "37", "description" : "Even though it's located in Rome, Vatican City has been an independent state since 1929 with its own flag, coins and stamps. It even has its own militia, the Swiss Guard, which protects this state, the Pope and the 800 full-time citizens and visiting residents. The first impressive site is St. Peter's Square itself designed by Bernini in the late 17th century. As long as you're dressed appropriately (no bare shoulders or shorts or skirts above the knee), you may enter St. Peter's Basilica and see Michelangelo's Pietá, a stunningly beautiful and sad sculpture. Continue up to the roof where you can take in the view of the large square and city beyond. Also contained in the Vatican's walls, the Vatican Museums hold Italian masterpieces, including Michelangelo's painted ceiling at the Sistine Chapel."],
                ["name" : "Galleria Borghese", "price" : "18", "description" : "The Galleria Borghese (English: Borghese Gallery) is an art gallery in Rome, Italy, housed in the former Villa Borghese Pinciana. At the outset, the gallery building was integrated with its gardens, but nowadays the Villa Borghese gardens are considered a separate tourist attraction. The Galleria Borghese houses a substantial part of the Borghese collection of paintings, sculpture and antiquities, begun by Cardinal Scipione Borghese, the nephew of Pope Paul V (reign 1605–1621). The Villa was built by the architect Flaminio Ponzio, developing sketches by Scipione Borghese himself, who used it as a villa suburbana, a country villa at the edge of Rome."]
            ],
            "outdoors" : [
                ["name" : "Villa Borghese Park", "price" : "0", "description" : "Dubbed the central park of Rome, Villa Borghese is a favorite for tourists and the locals. The resurrection of the park was commissioned during the 17th century and used by the Borghese and Bonaparte families. Though, it's not the largest park in Rome it is the most popular thanks to its central location and its beautiful scenery. Villa Borghese is also famous for its historical buildings and world-class museums such as the Galleria Borghese, a children's cinema, and a place where you can rent bikes. There are many places to sit and take some time out or have a picnic, but along the banks of little late are some of the prettiest."],
                ["name" : "Roman Forum", "price" : "0", "description" : "In ancient Rome, the Forum was the center of city life, playing host to festivals, celebrations, funerals and rituals. The city grew around this grassy area that was empty marshland until the 7th century B.C. The area lost its luster and fell to waste around the 8th century and remained that way until excavations in the early 20th century. Today, you can pick up a map for a self-guided tour of the structures and arches or join a tour group for a more detailed history of the area. Then climb to the top of Palatine Hill for sweeping views of the city."],
                ["name" : "A true foodie adventure in Rome’s most picturesque quarter", "price" : "100", "description" : """
                    Formerly known as the Daylight Trastevere Food Tour, Trastevere for Foodies is a delight for the true foodie looking to get a real flavor of Roman life, through our food! With its narrow cobblestone streets and laneways, Trastevere is the most picturesque Roman neighborhood and one you need to visit during your stay. During the day, it’s like a small village with timeless and artisan shops serving the same local families for generations – many of which we’ll visit together, tasting the amazing food and exploring these local spots along the way.
                    On this 4-hour guided walking food tour we visit the colorful outdoor food market and meet some of the stallholders who have been selling their produce there for generations. You’ll also visit local food stores and talk to the wonderful families working hard to preserve Roman food traditions. This tour features some unique cultural and historical sites that few tourists get an opportunity to see. Join us for a day living like a true local!
                    """]
            ],
            "nightlife" : [
                ["name" : "Rosati", "price" : "10", "description" : "Rosati opened on the Piazza del Popolo in 1922 and soon became a cornerstone of the vigorous, intellectual café and bar culture of Rome’s artists, poets and leftist thinkers. Sip on creative and interesting cocktails, and get into the spirit of the place with some invigorating intellectual discussion that continues on into the night."],
                ["name" : "Teatro dell’Opera di Roma", "price" : "80", "description" : "With acoustics to rival the world’s great auditoria, a night at Rome’s opera house can be a stirring and spectacular experience, with an acclaimed and talented opera company performing classics and recent works. The venue also has plenty for those left unmoved by opera, including ballet and classical symphony concerts. In the summer the opera company performs at the third-century ruins of the Baths of Caracalla, an outstanding and atmospheric open-air site that complements the passion and intensity of opera. It can make for a truly privileged and spectacular experience for long-time opera lovers and skeptics alike."],
                ["name" : "Auditorium Parco della Musica", "price" : "10", "description" : "An immense venue for arts, the stunning Auditorium Parco della Musica is at the forefront of Rome’s flourishing modern cultural life. It hosts the biggest names and performances across a dizzying variety of genres and disciplines, from music, dance, theater, comedy and cabaret to painting, photography, journalism, poetry, science and history. The wide-ranging program has something to suit all tastes, and the Auditorium’s four atmospheric performance spaces – from the intimate 300-person theater to the immense, 3,500-person summer amphitheater – are evocative complements to the events they host. The Auditorium stands above the still-visible ruins of an Ancient Roman villa, and its own design incorporates local materials and architectural traditions, giving a quintessentially Roman flavor to the experience of the arts that it offers. Exclusive private performances can be arranged and spectacular corporate functions, from cocktail receptions to lavish gala dinners, are eagerly accommodated and organized."]
            ]
        ],
        "Beijing" : [
            "cultural" : [
                ["name" : "Summer Palace", "price" : "79", "description" : "The Summer Palace, is a vast ensemble of lakes, gardens and palaces in Beijing, China. It was an imperial garden in Qing Dynasty. Mainly dominated by Longevity Hill and Kunming Lake, it covers an expanse of 2.9 square kilometres (1.1 sq mi), three-quarters of which is water."],
                ["name" : "National Art Museum of China (NAMOC) ", "price" : "3", "description" : "Chinese art developed almost completely separately from that in the west and, considering its age, imported techniques and mediums have only become popular relatively recently. NAMOC was opened by Chairman Mao in 1963 to showcase modern Chinese art and now sports a great collection of traditional Chinese ink and wash paintings as well as the sort of socialist-themed pieces you would expect at a museum set up by the communist party. But don't make the mistake of thinking that this museum is stuffy; though the exhibited works are hardly likely to contain anything too controversial, there's a smattering of contemporary pieces that have sent international collectors into a tizz."],
                ["name" : "About Forbidden City", "price" : "6", "description" : "The Forbidden City in Beijing was constructed in the late fifteenth century and was initially known as the Palace Museum. Today, the city consists of over 9,000 rooms for accommodation and is spread over a huge area of 250 acres. The significance of the attraction in Beijing arises from the fact that in the ancient times, this place served as a home to the emperors and their families and was also the centre for holding ceremonial processions and conducting political agendas. What is worthy of attention at this landmark in Beijing is the traditional Chinese architecture that is an exemplary display of cultural and traditional developments adopted from the East Asia region. Today, this place is a declared World Heritage site for the largest collection of preserved wooden structures in the world."]
            ],
            "outdoors" : [
                ["name" : "Beijing Zoo", "price" : "3", "description" : "Beijing Zoo can be visited under a guided tour that will be perfect to explore the area in a systematic manner. You can spot a number of animals in this zoo including bears, wild cats and even pandas. Beijing Zoo is close to the metro station that makes it easily accessible. You will be amazed after visiting this space as there are some rare species of animals that will surely stun your mind. Make sure you do not touch any of the enclosures. Feeding the animals is strictly prohibited at Beijing Zoo. The managing staff at this zoo is not that active. Kids would love the visit to Beijing Zoo as it will help them learn about wildlife."],
                ["name" : "Olympic Park", "price" : "0", "description" : "Olympic Park can be visited easily as it is located in the Chaoyang District. This park is very attractive in terms of its setup. You can come here with your friends and family to spend a lovely time surrounded by nature. Olympic Park is located close to the main stadium and is also near to Bird’s Nest and Water Cube. At night, the whole area is well lit to offer a lovely view. There is a wall present close to Olympic Park that includes the names of the 2008 Olympic winners. Make sure you avoid your visit on the weekends as the place is too crowded. Subway is the best way to reach Olympic Park without any hassle"],
                ["name" : "Beijing Botanical Garden", "price" : "1", "description" : "Beijing Botanical Garden should be visited if you are a nature lover. There are a number of flower varieties present in this area that will surely impress your eyes. The early spring season is the perfect time to visit Beijing Botanical Garden. The air in this area is very fresh due to the presence of numerous plants and trees. The rose garden inside Beijing Botanical Garden is the most famous spot for the public. There are also lakes present inside Beijing Botanical Garden which makes the place worth visiting. There are even greenhouse chambers present that will help you learn about plant growth and preservation. The staff at Beijing Botanical Garden is very active."]
            ],
            "nightlife" : [
                ["name" : "About Vics NIGHTCLUB", "price" : "10", "description" : "The hottest and the hippest nightlife destination in Beijing, Vics NIGHTCLUB includes a sports bar, a restaurant, and a club. Swoon over the enigmatic vibe and the excellence of music showcased here. The talented DJs play a mix of pop, R&B, hip-hop, reggae and soul. The colorful lights, lanterns, and furniture, add to the ornate interiors of the restaurant. The staff is cordial and gives you a hospitable treatment. From food to music to décor, everything is inviting about this place. Their wide range of cocktails, mocktails, and other beverages spoil you for choice. Vics nightclub has a huge computer screen that lets VJs showcase their talent. The sound system is pleasingly loud, a huge relief from the ear deafening volumes of the usual clubs. So, trigger up your party rave and head to Vics Club."],
                ["name" : "About Long Jing Modern Tea House And Cocktail Lounge", "price" : "28", "description" : "Located at South Sanlitun, Long Jing Modern Tea House & Cocktail Lounge is the place to be. A teahouse by day and a cocktail bar by night, it is an excellent venue to drop in with your friends. If the brewed tea doesn’t get you going, gulp down one or two of their signature cocktails. Nicely decorated with a minimalistic approach, well-balanced sound system, and expert lighting makes it an ideal place to enjoy a cocktail. The staff employed is friendly and serve you with a smile. They have a simple concept – brew tea, mix booze, get drunk. The place has comfortable sofas and armchairs and low-lying tables. When here, the must-try cocktail is the Longjing. A blast of flavors evolve sip after sip. Another star on the drinks menu is a cocktail named ‘Rich’."],
                ["name" : "Slow Boat Brewery Taproom", "price" : "12", "description" : "Well-hidden down under a residential street, Slow Boat Brewery Taproom is home the largest selection of beer in Beijing. An amazing place to catch up with old friends or meet new people, it is a cool little bar with a selection of fifteen fine beer brands on tap. The hutong atmosphere and the lively vibe add to the charm of the place. This place also serves refreshments, limited but lip-smacking. When here, tuck into their Fry Burger stuffed with fries and handmade sodas. Talking about beer, there is a long list of North-American and core beer here. The Monkeys First IPA and Captain’s Pale Ale are highly recommended. The staff employed is extremely courteous and prices are reasonable. Slow Boat Brewery Taproom is the ultimate destination for your beer cravings in Beijing."]
            ]
        ]
    ]

    var culturalActivities: [[String : String]]
    var outdoorsActivities: [[String : String]]
    var nightlifeActivities: [[String : String]]

    
    init(cityName: String) {
        self.culturalActivities = Activities.activitiesData[cityName]!["cultural"]!
        self.outdoorsActivities = Activities.activitiesData[cityName]!["outdoors"]!
        self.nightlifeActivities = Activities.activitiesData[cityName]!["nightlife"]!
    }
}
